tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from django.urls import include, reverse_lazy, path

from tracker.ui import urls as ui_urls
from tracker.views import public, api, donateviews, user, auth

app_name = 'tracker'

api_patterns = ([
    path('', api.index, name='index'),
    path('add/', api.add, name='add'),
    path('command/', api.command, name='command'),
    path('delete/', api.delete, name='delete'),
    path('edit/', api.edit, name='edit'),
    path('me/', api.me, name='me'),
    path('search/', api.search, name='search'),

    path('ads/<int:event>/', api.ads, name='ads'),
    path('interstitial/', api.interstitial, name='interstitial'),
    path('interviews/<int:event>/', api.interviews),
    path('hosts/<int:event>/', api.hosts),
], 'api')

event_patterns = ([
    path('', public.index, name='index'),
    path('bids/', public.bidindex, name='bidindex'),
    path('bids/<int:pk>/', public.bid_detail, name='bid'),
    path('donate/', donateviews.donate, name='donate'),
    path('donate/return/', donateviews.paypal_return, name='paypal_return'),
    path('donate/cancel/', donateviews.paypal_cancel, name='paypal_cancel'),
    path('donations/', public.donationindex, name='donationindex'),
    path('donations/<int:pk>/', public.donation_detail, name='donation'),
    path('donors/', public.donorindex, name='donorindex'),
    path('donors/<int:pk>/', public.donor_detail, name='donor'),
    path('prizes/', public.prizeindex, name='prizeindex'),
    path('prizes/<int:pk>/', public.prize_detail, name='prize'),
    path('runs/', public.runindex, name='runindex'),
    path('runs/<int:pk>/', public.run_detail, name='run'),
], 'event')

urlpatterns = [
    path('', public.eventlist, name='index'),
    path('ui/', include(ui_urls, namespace='ui')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('paypal/ipn/', donateviews.ipn, name='ipn'),

    path('user/', user.user_index, name='user_index'),
    path('user/user_prize/<int:prize>', user.user_prize, name='user_prize'),
    path('user/prize_winner/<int:prize_win>', user.prize_winner, name='prize_winner',),
    path('user/submit_prize/<slug:event>', user.submit_prize, name='submit_prize'),
    path('user/register/', auth.register, name='register'),
    path(
        'user/confirm_registration/<uidb64>/<token>/',
        auth.confirm_registration,
        name='confirm_registration',
    ),
    # all urls below are served by standard Django views
    path(
        'user/login/',
        LoginView.as_view(template_name='tracker/login.html'),
        name='login',
    ),
    path('user/logout/', LogoutView.as_view(next_page='tracker:login'), name='logout',),
    path(
        'user/password_reset/',
        PasswordResetView.as_view(
            template_name='tracker/password_reset.html',
            email_template_name='tracker/email/password_reset.txt',
            html_email_template_name='tracker/email/password_reset.html',
            success_url=reverse_lazy('tracker:password_reset_done'),
        ),
        name='password_reset',
    ),
    path(
        'user/password_reset_done/',
        PasswordResetDoneView.as_view(template_name='tracker/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'user/password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='tracker/password_reset_confirm.html',
            success_url=reverse_lazy('tracker:password_reset_complete'),
        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='tracker/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    path(
        'user/password_change/',
        PasswordChangeView.as_view(
            template_name='tracker/password_change.html',
            success_url=reverse_lazy('tracker:password_change_done'),
        ),
        name='password_change',
    ),
    path(
        'user/password_change_done/',
        PasswordChangeDoneView.as_view(
            template_name='tracker/password_change_done.html'
        ),
        name='password_change_done',
    ),

    path('api/', include(api_patterns, namespace='api')),
    path('<slug:event>/', include(event_patterns, namespace='event')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/templates/base.html
{% load donation_tags %}
{% load static %}
{% load i18n %}

{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}{% endblock %}
        </title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">

        <style>
            #top {
                background-color: {% firstof event.header_color "var(--dark)" %};
                flex-shrink: 0;
                margin-bottom: 2rem;

                {% if event.header_image %}
                background-image: url("{{ event.header_image.url }}");
                background-position: {{ event.header_image_align }} center;
                background-repeat: no-repeat;
                {% endif %}
            }

            .opacity-50 {
                opacity: 0.5;
            }
        </style>

        <script src="{% static "jquery-3.5.1.slim.min.js" %}"></script>
        <script src="{% static "bootstrap.bundle.min.js" %}"></script>

        {% block head %}{% endblock %}
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <div class="d-flex flex-column overflow-auto vh-100">
            <div id="top">
                {% block nav %}
                <nav class="navbar navbar-expand navbar-dark small py-0">
                    <div class="container px-0">
                        <div class="collapse navbar-collapse">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'tracker:index' %}">
                                        <i class="fa fa-home"></i>
                                    </a>
                                </li>
                                {% if events and event %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                                        {{ event.name }}
                                    </a>
                                    <div class="dropdown-menu">
                                        {% for e in events reversed %}
                                        <a class="dropdown-item{% if e.pk == event.pk %} active{% endif %}"
                                            href="{% event_url e 'tracker:event:index' %}">
                                            {{ e.name }}
                                        </a>
                                        {% endfor %}
                                    </div>
                                </li>
                                {% endif %}
                            </ul>
                            <ul class="navbar-nav ml-auto">
                                {% if request.user.is_staff %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'admin:index' %}">
                                        {% trans "Site Administration" %}
                                    </a>
                                </li>
                                {% endif %}
                                {% if languages|length > 1 %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                                        {{ LANGUAGE_CODE|language_name }}
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        {% for language in languages %}
                                        <a class="dropdown-item{% if language.code == LANGUAGE_CODE %} active{% endif %}" href="#"
                                            onclick="setLanguage('{{ language.code }}')">
                                            {{ language.name }}
                                        </a>
                                        {% endfor %}
                                    </div>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
                {% if event %}
                <nav class="navbar navbar-expand-sm navbar-dark pt-0">
                    <div class="container px-0">
                        <button class="navbar-toggler w-100" type="button" data-toggle="collapse" data-target="#navbarCollapse">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarCollapse">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% event_url event 'tracker:event:index' %}">{% trans "Home" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% event_url event 'tracker:event:runindex' %}">{% trans "Runs" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                        href="{% event_url event 'tracker:event:prizeindex' %}">{% trans "Prizes" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% event_url event 'tracker:event:bidindex' %}">{% trans "Incentives" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                        href="{% event_url event 'tracker:event:donorindex' %}">{% trans "Donors" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                        href="{% event_url event 'tracker:event:donationindex' %}">{% trans "Donations" %}</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-auto">
                                {% if not event.locked and event.allow_donations %}
                                <li class="nav-item ml-lg-4">
                                    <a class="btn btn-outline-warning btn-block font-weight-bold px-4 text-uppercase"
                                        href="{% event_url event 'tracker:event:donate' %}">
                                        {% trans "Donate" %}
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
                {% endif %}
                {% endblock %}

                {% block jumbotron %}{% endblock %}
            </div>

            <div class="container flex-fill pb-4">
                {% block content %}{% endblock %}
            </div>
        </div>

        <form id="languageForm" action="{% url 'tracker:set_language' %}" method="post">
            {% csrf_token %}

            <input type="hidden" name="next" value="{{ request.get_full_path }}" />
            <input type="hidden" name="language" value="{{ LANGUAGE_CODE }}" />
        </form>

        <script>
            function setLanguage(code) {
                const form = $("#languageForm");
                const languageInput = $("input[name='language']", languageForm);

                languageInput.val(code);
                form.submit();
            }
        </script>
    </body>
</html>

tracker/templates/error.html
{% extends "base.html" %}

{% load donation_tags %}
{% load i18n %}

{% block title %}
{% trans "Error" %}
{% endblock %}

{% block body_class %}bg-dark text-white{% endblock %}

{% block content %}
  <div class="justify-content-center d-flex flex-column h-100">
    <div class="text-center">
      <h3 class="mb-3">
        {% block message %}
        {% trans "Something strange happened" %}
        {% endblock %}
      </h3>
      <a class="btn btn-link text-white-50" href="{% url 'tracker:index' %}">
        {% trans "Go to homepage" %}
      </a>
    </div>
  </div>
{% endblock %}

tracker/templates/form_innards.html
{% if csrf_token %}
  {% csrf_token %}
{% endif %}

{% if showrequired %}
<span style="color:red"><small>(* = required)</small></span> 
<br />
<br />
{% endif %}
{% for error in form.non_field_errors %}
<span style="color:red">
  <strong>{{ error|escape }}</strong>
</span>
<br />
{% endfor %}

{% for field in form.hidden_fields %}
  {% if field.errors %}
  <span style="color:red">
    <strong>{{ field.errors | escape }}</strong><br />
  </span>
  {% endif %}
  {{ field }}
{% endfor %}

{% for field in form.visible_fields %}
  {{ field.label_tag }} {% if field.field.required and showrequired %} <span style="color:red">*</span> {% endif %}
  {% if field.errors %}
  <span style="color:red">
    <strong>{{ field.errors | escape }}</strong>
  </span>
  {% endif %}
  {% if field.help_text %}
      <small>{{ field.help_text }}</small>
      <br />
  {% endif %}
  {{ field }}
  <br />
  <br />
{% endfor %}

tracker/templates/standardform.html
{% load donation_tags %}

<form id="{{ formid }}" method="post" {% if action %}action="{{ action }}"{% endif %}>
  {% form_innards form showrequired=showrequired %}
  <p><input type="submit" value="{{ submittext }}" /></p>
</form>