tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from django.urls import include, reverse_lazy, path

from tracker.ui import urls as ui_urls
from tracker.views import public, api, donateviews, user, auth

app_name = 'tracker'

api_patterns = ([
    path('', api.index, name='index'),
    path('add/', api.add, name='add'),
    path('command/', api.command, name='command'),
    path('delete/', api.delete, name='delete'),
    path('edit/', api.edit, name='edit'),
    path('me/', api.me, name='me'),
    path('search/', api.search, name='search'),

    path('ads/<int:event>/', api.ads, name='ads'),
    path('interstitial/', api.interstitial, name='interstitial'),
    path('interviews/<int:event>/', api.interviews),
    path('hosts/<int:event>/', api.hosts),
], 'api')

event_patterns = ([
    path('', public.index, name='index'),
    path('bids/', public.bidindex, name='bidindex'),
    path('bids/<int:pk>/', public.bid_detail, name='bid'),
    path('donate/', donateviews.donate, name='donate'),
    path('donate/return/', donateviews.paypal_return, name='paypal_return'),
    path('donate/cancel/', donateviews.paypal_cancel, name='paypal_cancel'),
    path('donations/', public.donationindex, name='donationindex'),
    path('donations/<int:pk>/', public.donation_detail, name='donation'),
    path('donors/', public.donorindex, name='donorindex'),
    path('donors/<int:pk>/', public.donor_detail, name='donor'),
    path('prizes/', public.prizeindex, name='prizeindex'),
    path('prizes/<int:pk>/', public.prize_detail, name='prize'),
    path('runs/', public.runindex, name='runindex'),
    path('runs/<int:pk>/', public.run_detail, name='run'),
], 'event')

urlpatterns = [
    path('', public.eventlist, name='index'),
    path('ui/', include(ui_urls, namespace='ui')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('paypal/ipn/', donateviews.ipn, name='ipn'),

    path('user/', user.user_index, name='user_index'),
    path('user/user_prize/<int:prize>', user.user_prize, name='user_prize'),
    path('user/prize_winner/<int:prize_win>', user.prize_winner, name='prize_winner',),
    path('user/submit_prize/<slug:event>', user.submit_prize, name='submit_prize'),
    path('user/register/', auth.register, name='register'),
    path(
        'user/confirm_registration/<uidb64>/<token>/',
        auth.confirm_registration,
        name='confirm_registration',
    ),
    # all urls below are served by standard Django views
    path(
        'user/login/',
        LoginView.as_view(template_name='tracker/login.html'),
        name='login',
    ),
    path('user/logout/', LogoutView.as_view(next_page='tracker:login'), name='logout',),
    path(
        'user/password_reset/',
        PasswordResetView.as_view(
            template_name='tracker/password_reset.html',
            email_template_name='tracker/email/password_reset.txt',
            html_email_template_name='tracker/email/password_reset.html',
            success_url=reverse_lazy('tracker:password_reset_done'),
        ),
        name='password_reset',
    ),
    path(
        'user/password_reset_done/',
        PasswordResetDoneView.as_view(template_name='tracker/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'user/password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='tracker/password_reset_confirm.html',
            success_url=reverse_lazy('tracker:password_reset_complete'),
        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='tracker/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    path(
        'user/password_change/',
        PasswordChangeView.as_view(
            template_name='tracker/password_change.html',
            success_url=reverse_lazy('tracker:password_change_done'),
        ),
        name='password_change',
    ),
    path(
        'user/password_change_done/',
        PasswordChangeDoneView.as_view(
            template_name='tracker/password_change_done.html'
        ),
        name='password_change_done',
    ),

    path('api/', include(api_patterns, namespace='api')),
    path('<slug:event>/', include(event_patterns, namespace='event')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/views/donateviews.py
import datetime
import json
import logging
import random
import traceback
import post_office.mail
import pytz
import os

from decimal import Decimal
from gettext import gettext as _

from django.conf import settings
from django.db import transaction
from django.utils import translation
from django.db.models import F
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.middleware import csrf
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from paypal.standard.forms import PayPalPaymentsForm

from tracker import forms, models, eventutil, viewutil, paypalutil, search_filters
from webpack_manifest import webpack_manifest

from tracker.decorators import no_querystring
from tracker.models import Bid

from ..serializers import DecimalEncoder
from .common import tracker_response
from .public import get_bid_info

__all__ = [
    'paypal_cancel',
    'paypal_return',
    'donate',
    'ipn',
]

logger = logging.getLogger(__name__)


@csrf_exempt
def paypal_cancel(request, event):
    return tracker_response(request, 'tracker/paypal_cancel.html', {
        'event': viewutil.get_event(event),
    })


@csrf_exempt
def paypal_return(request, event):
    return tracker_response(request, 'tracker/paypal_return.html', {
        'event': viewutil.get_event(event),
    })


def process_form(request, event):
    bidsFormPrefix = 'bidsform'
    if request.method == 'POST':
        commentform = forms.DonationEntryForm(event=event, data=request.POST)
        if commentform.is_valid():
            bidsform = forms.DonationBidFormSet(
                amount=commentform.cleaned_data['amount'],
                data=request.POST,
                prefix=bidsFormPrefix,
            )
            if bidsform.is_valid():
                with transaction.atomic():
                    donation = models.Donation(
                        amount=commentform.cleaned_data['amount'],
                        timereceived=pytz.utc.localize(datetime.datetime.utcnow()),
                        commentlanguage=translation.get_language_from_request(request),
                        domain='PAYPAL',
                        domainId=str(random.getrandbits(128)),
                        event=event,
                    )
                    if commentform.cleaned_data['comment']:
                        donation.comment = commentform.cleaned_data['comment']
                        donation.commentstate = 'PENDING'
                    donation.requestedvisibility = commentform.cleaned_data[
                        'requestedvisibility'
                    ]
                    donation.requestedalias = commentform.cleaned_data['requestedalias']
                    donation.requestedemail = commentform.cleaned_data['requestedemail']
                    donation.requested_receipt = commentform.cleaned_data['requested_receipt']
                    donation.currency = event.paypalcurrency
                    donation.save()
                    for bidform in bidsform:
                        if (
                            'bid' in bidform.cleaned_data
                            and bidform.cleaned_data['bid']
                        ):
                            bid = bidform.cleaned_data['bid']
                            if bid.allowuseroptions:
                                # unfortunately, you can't use get_or_create when using a non-atomic transaction
                                # this does technically introduce a race condition, I'm just going to hope that two people don't
                                # suggest the same option at the exact same time
                                # also, I want to do case-insensitive comparison on the name
                                try:
                                    bid = models.Bid.objects.get(
                                        event=bid.event,
                                        speedrun=bid.speedrun,
                                        name__iexact=bidform.cleaned_data[
                                            'customoptionname'
                                        ],
                                        parent=bid,
                                    )
                                except models.Bid.DoesNotExist:
                                    bid = models.Bid.objects.create(
                                        event=bid.event,
                                        speedrun=bid.speedrun,
                                        name=bidform.cleaned_data['customoptionname'],
                                        parent=bid,
                                        state='PENDING',
                                        istarget=True,
                                    )
                            donation.bids.add(
                                models.DonationBid(
                                    bid=bid,
                                    amount=Decimal(bidform.cleaned_data['amount']),
                                ),
                                bulk=False,
                            )
                    donation.full_clean()
                    donation.save()

                paypal_dict = {
                    'amount': str(donation.amount),
                    'cmd': '_donations',
                    'business': donation.event.paypalemail,
                    'image_url': donation.event.paypalimgurl,
                    'item_name': donation.event.receivername,
                    'notify_url': request.build_absolute_uri(reverse('tracker:ipn')),
                    'return': request.build_absolute_uri(
                        reverse('tracker:event:paypal_return', args=(donation.event.short,))
                    ),
                    'cancel_return': request.build_absolute_uri(
                        reverse('tracker:event:paypal_cancel', args=(donation.event.short,))
                    ),
                    'custom': str(donation.id) + ':' + donation.domainId,
                    'currency_code': donation.event.paypalcurrency,
                    'no_shipping': 0,
                }
                # Create the form instance
                form = PayPalPaymentsForm(button_type='donate', initial=paypal_dict)
                context = {'event': donation.event, 'form': form}
                return (
                    tracker_response(
                        request, 'tracker/paypal_redirect.html', context
                    ),
                    None,
                )
        else:
            bidsform = forms.DonationBidFormSet(
                amount=Decimal('0.00'), data=request.POST, prefix=bidsFormPrefix
            )
            bidsform.is_valid()
    else:
        commentform = forms.DonationEntryForm(event=event)
        bidsform = forms.DonationBidFormSet(
            amount=Decimal('0.00'), prefix=bidsFormPrefix
        )
    return commentform, bidsform


@csrf_protect
@no_querystring
def donate(request, event):
    bundle = webpack_manifest.load(
        os.path.abspath(
            os.path.join(os.path.dirname(__file__), '../ui-tracker.manifest.json')
        ),
        settings.STATIC_URL,
        debug=settings.DEBUG,
        timeout=60,
        read_retry=None,
    )

    event = viewutil.get_event(event)

    if event.locked:
        raise Http404

    if not event.allow_donations:
        return tracker_response(
            request,
            'tracker/donate.html',
            {
                'event': event,
            },
        )

    commentform, bidsform = process_form(request, event)

    if not bidsform:
        return commentform

    def event_info(event):
        result = {
            'id': event.id,
            'name': event.name,
            'receiver_name': event.receivername,
            'paypal_currency': event.paypalcurrency,
            'minimum_donation': event.minimumdonation,
            'donation_notes': event.donation_notes,
        }

        return result

    def bid_info(bid):
        result = {
            'id': bid.id,
            'parent': bid.parent_id,
            'name': bid.name,
            'description': bid.description,
            'short_description': bid.shortdescription,
            'total': bid.total,
            'goal': bid.goal,
        }

        if bid.speedrun:
            result['speedrun'] = {
                'id': bid.speedrun.id,
                'name': bid.speedrun.name,
                'category': bid.speedrun.category,
            }

        if bid.allowuseroptions:
            result['allow_user_options'] = True
            result['option_max_length'] = bid.option_max_length

        return result

    def prize_info(prize):
        result = {
            'id': prize.id,
            'name': prize.name,
            'description': prize.description,
            'minimumbid': prize.minimumbid,
            'maximumbid': prize.maximumbid,
            'keyword': prize.keyword,
            'sumdonations': prize.sumdonations,
            'url': prize.get_absolute_url(),
        }

        return result

    bids = search_filters.run_model_query('allbids', {'state': 'OPENED', 'event': event.id})
    prizes = search_filters.run_model_query('prize', {'feed': 'current', 'event': event.id})

    bidsArray = [bid_info(bid) for bid in bids]
    prizesArray = [prize_info(prize) for prize in prizes]

    def to_json(value):
        return value.id if hasattr(value, 'id') else value

    initialData = {
        k: to_json(commentform.cleaned_data[k])
        for k, v in commentform.fields.items()
        if commentform.is_bound and k in commentform.cleaned_data
    }

    initialData['bids'] = [
        {
            k: to_json(form.cleaned_data[k])
            for k, v in form.fields.items()
            if k in form.cleaned_data
        }
        for form in bidsform.forms
        if form.is_bound
    ]

tracker/templates/tracker/bid.html
{% extends "base.html" %}

{% load donation_tags %}
{% load i18n %}

{% block title %}
{{ bid.name }} - {{ event.name }} - {% trans "Donation Tracker" %}
{% endblock %}

{% block jumbotron %}
<div class="bg-transparent jumbotron jumbotron-fluid m-0 text-white">
    <div class="container">
        <div class="text-white-50">
            <a class="text-reset" href="{% event_url event 'tracker:event:index' %}">
                {{ event.name }}
            </a>
            <i class="fa fa-angle-right mx-2"></i>
            <a class="text-reset" href="{% event_url event 'tracker:event:bidindex' %}">
                {% trans "Incentives" %}
            </a>
            {% for ancestor in bid.ancestors %}
            <i class="fa fa-angle-right mx-2"></i>
            <a class="text-reset" href="{% event_url event 'tracker:event:bid' pk=ancestor.pk %}">
                {{ ancestor.name }}
            </a>
            {% endfor %}
        </div>
        <h1 class="m-0">{{ bid.name }}</h1>
        <ul class="h5 list-inline mb-4 text-white-50">
            <li class="list-inline-item">
                {% if bid.speedrun %}
                <a class="text-reset" href="{% event_url event 'tracker:event:run' pk=bid.speedrun.pk %}">
                    <span class="h5">{{ bid.speedrun.name }}</span>
                    <span class="font-weight-normal">({{ bid.speedrun.category }})</span>
                </a>
                {% else %}
                {% trans "Event Wide" %}
                {% endif %}
            </li>
        </ul>
        <ul class="lead list-inline m-0">
            <li class="list-inline-item mr-4">
                <div class="small text-white-50">{% trans "Amount" %}</div>
                <div class="h5 m-0">{% event_money event bid.total %}</span>
            </li>
            {% if bid.goal %}
            <li class="list-inline-item mr-4">
                <div class="small text-white-50">{% trans "Goal" %}</div>
                <div class="h5 m-0">{% event_money event bid.goal %}</div>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

{% block content %}
{% if bid.description %}
<div class="row mb-4">
    <div class="col-3">
        <h5>{% trans "Description" %}</h5>
    </div>
    <div class="col">
        {{ bid.description|forumfilter }}
    </div>
</div>
{% endif %}

{% if bid.istarget %}
<div class="row mb-4">
    <div class="col-3">
        <h5>{% trans "Donations" %}</h5>
    </div>
    <div class="col">
        {% if donations %}
        <div class="card shadow">
            <table class="m-0 table table-borderless">
                <thead class="thead-light">
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <th width="250">{% trans "Date" %}</th>
                        <th width="125" class="px-4 text-right">{% trans "Amount" %}</th>
                    </tr>
                </thead>
                {% for donation in donations %}
                <tr>
                    <td>
                        {% include "tracker/partials/donor_link.html" with donor=donation.donor_cache only %}
                    </td>
                    <td class="datetime">
                        <time datetime="{{ donation.timereceived|date:"c" }}">
                            {{ donation.timereceived|date:"DATETIME_FORMAT" }}
                        </time>
                    </td>
                    <td class="text-right">
                        <a href="{% event_url event 'tracker:event:donation' pk=donation.id %}">{% event_money event donation.amount %}</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% else %}
        <div class="text-muted">
            {% trans "No donations for this option yet." %}
        </div>
        {% endif %}
    </div>
</div>
{% elif not bid.goal %}
<div class="row mb-4">
    <div class="col-3">
        <h5>{% trans "Options" %}</h5>
    </div>
    <div class="col">
        {% if bid.children %}
        <div class="card shadow">
            <table class="m-0 table table-borderless">
                <thead class="thead-light">
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <th width="125" class="text-right">{% trans "Amount" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for option in bid.children %}
                    <tr>
                        <td>
                            <a href="{% event_url event 'tracker:event:bid' pk=option.id %}">
                                {{ option.name }}
                            </a>
                        </td>
                        <td class="text-right">
                            {% event_money event option.amount %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="mt-4">
            {% include "tracker/partials/paginator.html" %}
        </div>
        {% else %}
        <div class="bg-primary card text-center text-white">
            <div class="card-body">
                {% trans "No options yet, submit one while donating." %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endif %}
{% endblock %}

tracker/templates/tracker/contributor_prize.html
{% extends "base.html" %}

{% load donation_tags %}
{% load i18n %}

{% block title %}{% trans "Prize Info" %}{% endblock %}

{% block content %}

<h3>{{ prize.name }}</h3>

{% if prize.state == 'PENDING' %}
  <p>
  This prize is still pending acceptance for the event.
  </p>
{% elif prize.state == 'DENIED' %}
  <p>
  Unfortunately we were not able to accept this prize.
  </p>
{% endif %}

{% if prize.reviewnotes %}
<p>
<b>Prize Coordinator Notes:</b> {{ prize.reviewnotes }}
</p>
{% endif %}

{% if prize.state == 'ACCEPTED' %}

{% if formset %}
  <h4>Winner{{ formset|length|pluralize }}</h4>

  {% if formset|length > 1 %}
  <small>Note: Please enter and save shipping details for each winner separately</small>
  {% endif %}

  <form id="prizesubmmision-{{forloop.counter}}" method="post">

  <ul>
  {% for form in formset %}
    {{ formset.management_form }}

    {% with form.instance as prize_winner %}
    <li>
      {% include 'tracker/partials/donor_link.html' with donor=prize_winner.winner only %} <i>({{ prize_winner.acceptcount }} cop{{ prize_winner.acceptcount|pluralize:"y,ies" }}{% if prize_winner.pendingcount > 1 %},&nbsp;{{ prize_winner.pendingcount }} cop{{ prize_winner.pendingcount|pluralize:"y,ies" }} pending{% endif %})</i> {% if form.saved %}<span style="color:blue">Saved</span>{% endif %}<br />
      <b>Mailing Address:</b> <br />
      {% include 'tracker/partials/donor_address.html' with donor=prize_winner.winner only %}
      <br />
      {% if prize_winner.winnernotes %}
      <p>
      Winner Notes: {{ prize_winner.winnernotes }}
      </p>
      {% endif %}

      {% form_innards form showrequired=False %}

      <input type="submit" name="form-saved-{{forloop.counter}}" value="Save">
      <br />
      <br />
    </li>
    {% endwith %}
  {% endfor %}
  </ul>

  </form>
{% endif %}

{% if pendingWinners %}
  <p>There {{ pendingWinners.count|pluralize:"is,are" }} {{ pendingWinners.count }} {% if formset %}additional {% endif %}pending winner{{ pendingWinners.count|pluralize:"s" }} for this prize.</p>
{% elif not formset %}
  <p>There are currently no winners for this prize.</p>
{% endif %}

{% endif %}

<br />
<a href="{% url 'tracker:user_index' %}">Back to Self Service index</a>
<br />

{% endblock %}

tracker/templates/tracker/donate.html
{% extends "base.html" %}

{% load donation_tags %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans "Donate" %} - {{ event.name }} - {% trans "Donation Tracker" %}
{% endblock %}

{% block head %}
{% if bundle %}
{{ bundle.css|safe }}
{% endif %}
{% endblock %}

{% block jumbotron %}
<div class="bg-transparent jumbotron jumbotron-fluid m-0 text-white">
  <div class="container">
    <div class="text-white-50">
      <a class="text-reset" href="{% event_url event 'tracker:event:index' %}">{{ event.name }}</a>
    </div>
    <h1>{% trans "Donate" %}</h1>
    <div class="lead">
      {% blocktrans with receivername=event.receivername trimmed %}
      100% of your donation goes directly to <strong>{{ receivername }}</strong>!
      {% endblocktrans %}
    </div>
  </div>
</div>
{% endblock %}


{% block content %}
{% if event.allow_donations %}
{% if bundle %}
<div id="app"></div>

<script type="application/json" id="__APP_DATA__">
  {
    "props": {{ props|safe }}
  }
</script>

{{ bundle.js|safe }}
{% endif %}
{% else %}
<div class="alert alert-warning text-center">
  {% trans "This event doesn't allow donations at the moment, please try again later." %}
</div>
{% endif %}
{% endblock %}

tracker/templates/tracker/donors.html
{% extends "base.html" %}

{% load donation_tags %}
{% load i18n %}

{% block title %}
{% trans "Donors" %} - {{ event.name }} - {% trans "Donation Tracker" %}
{% endblock %}

{% block jumbotron %}
<div class="bg-transparent jumbotron jumbotron-fluid m-0 text-white">
    <div class="container">
        <div class="text-white-50">
            <a class="text-reset" href="{% event_url event 'tracker:event:index' %}">{{ event.name }}</a>
        </div>
        <h1>{% trans "Donors" %}</h1>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="card shadow">
    <table class="m-0 table table-borderless">
        <thead class="thead-light">
            <tr>
                <th>{% trans "Name" %}</th>
                <th width="100" class="text-right">{% trans "Count" %}</th>
                <th width="125" class="text-right">{% trans "Total" %}</th>
                <th width="200" class="text-right">{% trans "Maximum Amount" %}</th>
                <th width="200" class="text-right">{% trans "Average Amount" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for donor in donors %}
            {% if donor.donation_count > 0 %}
            <tr>
                <td>
                    {% include "tracker/partials/donor_link.html" with donor=donor only %}
                </td>
                <td class="text-right">
                    {{ donor.donation_count }}
                </td>
                <td class="text-right">
                    {% event_money event donor.donation_total %}
                </td>
                <td class="text-right">
                    {% event_money event donor.donation_max %}
                </td>
                <td class="text-right">
                    {% event_money event donor.donation_avg %}
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="mt-4">
    {% include "tracker/partials/paginator.html" %}
</div>
{% endblock %}

tracker/templates/tracker/event.html
{% extends "base.html" %}

{% load donation_tags %}
{% load i18n %}
{% load static %}

{% block title %}
{{ event.name }} - {% trans "Donation Tracker" %}
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static "bootstrap.min.css" %}">
{% endblock %}

{% block jumbotron %}
<div class="bg-transparent jumbotron jumbotron-fluid m-0 text-white">
    <div class="container">
        <h1 class="m-0">{{ event.name }}</h1>
        <ul class="h5 list-inline mb-4 text-white-50">
            <li class="list-inline-item">
                <time datetime="{{ event.datetime|date:"c" }}">
                    {{ event.datetime|date:"DATETIME_FORMAT" }}
                </time>
            </li>
        </ul>
        <ul class="lead list-inline m-0">
            <li class="list-inline-item mr-4">
                <div class="small text-white-50">{% trans "Total" %}</div>
                <div class="h5 m-0">{% event_money event agg.amount %}</span>
            </li>
            <li class="list-inline-item mr-4">
                <div class="small text-white-50">{% trans "Maximum Amount" %}</div>
                <div class="h5 m-0">{% event_money event agg.max %}</div>
            </li>
            <li class="list-inline-item mr-4">
                <div class="small text-white-50">{% trans "Average Amount" %}</div>
                <div class="h5 m-0">{% event_money event agg.avg %}</div>
            </li>
            <li class="list-inline-item mr-4">
                <div class="small text-white-50">{% trans "Median Amount" %}</div>
                <div class="h5 m-0">{% event_money event agg.median %}</div>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
    <div class="col mb-4">
        <div class="card shadow">
            <div class="no-gutters row">
                <div class="align-items-center col d-flex p-4 position-static">
                    <a class="h5 m-0 stretched-link" href="{% event_url event 'tracker:event:runindex' %}">
                        {% trans "Runs" %}
                    </a>
                </div>
                <div class="align-items-center col col-auto d-flex h5 m-0 p-4 text-muted">
                    {{ count.runs }}
                </div>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card shadow">
            <div class="no-gutters row">
                <div class="align-items-center col d-flex p-4 position-static">
                    <a class="h5 m-0 stretched-link" href="{% event_url event 'tracker:event:prizeindex' %}">
                        {% trans "Prizes" %}
                    </a>
                </div>
                <div class="align-items-center col col-auto d-flex h5 m-0 p-4 text-muted">
                    {{ count.prizes }}
                </div>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card shadow">
            <div class="no-gutters row">
                <div class="align-items-center col d-flex p-4 position-static">
                    <a class="h5 m-0 stretched-link" href="{% event_url event 'tracker:event:bidindex' %}">
                        {% trans "Incentives" %}
                    </a>
                </div>
                <div class="align-items-center col col-auto d-flex h5 m-0 p-4 text-muted">
                    {{ count.bids }}
                </div>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card shadow">
            <div class="no-gutters row">
                <div class="align-items-center col d-flex p-4 position-static">
                    <a class="h5 m-0 stretched-link" href="{% event_url event 'tracker:event:donorindex' %}">
                        {% trans "Donors" %}
                    </a>
                </div>
                <div class="align-items-center col col-auto d-flex h5 m-0 p-4 text-muted">
                    {{ count.donors }}
                </div>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card shadow">
            <div class="no-gutters row">
                <div class="align-items-center col d-flex p-4 position-static">
                    <a class="h5 m-0 stretched-link" href="{% event_url event 'tracker:event:donationindex' %}">
                        {% trans "Donations" %}
                    </a>
                </div>
                <div class="align-items-center col col-auto d-flex h5 m-0 p-4 text-muted">
                    {{ agg.count }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tracker/templates/tracker/index.html
{% extends "base.html" %}

{% load donation_tags %}
{% load i18n %}

{% block title %}
{% trans "Donation Tracker" %}
{% endblock %}

{% block jumbotron %}
<div class="bg-transparent jumbotron jumbotron-fluid m-0 text-white">
  <div class="container">
    <h1>{% trans "All Events" %}</h1>
    <div class="lead">
      {% trans "Select an event below to access it" %}
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
{% for event in events %}
<div class="card mb-4 shadow">
  <div class="no-gutters row">
    <div class="col position-static">
      <div class="card-body">
        <a class="h5 m-0 stretched-link" href="{% url pattern event=event.short %}">
          {{ event.name }}
        </a>
        <ul class="list-inline m-0">
          <li class="list-inline-item">
            <time datetime="{{ event.datetime|date:"c" }}">
              {{ event.datetime|date:"DATETIME_FORMAT" }}
            </time>
          </li>
        </ul>
      </div>
    </div>
    <div class="align-items-center col col-auto d-flex">
      <div class="card-body">
        <ul class="list-inline m-0">
          <li class="list-inline-item px-2">
            <div class="small text-muted">{% trans "Total" %}</div>
            <div class="h6 m-0">{% event_money event event.amount %}</div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}